// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx7V8vC-uxqdyUWK7h_ZNvfG4IkSqX_6U',
    appId: '1:884285617554:web:1cdd65b1d9c2638d5dbd4b',
    messagingSenderId: '884285617554',
    projectId: 'rede-social-app-b458e',
    authDomain: 'rede-social-app-b458e.firebaseapp.com',
    storageBucket: 'rede-social-app-b458e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt9-pYEI6JhKVMHcPtM1YXsIBMjLyjhxs',
    appId: '1:884285617554:android:58f7e918190d3f2a5dbd4b',
    messagingSenderId: '884285617554',
    projectId: 'rede-social-app-b458e',
    storageBucket: 'rede-social-app-b458e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3FWIkV6cxq3gvnioTIzSRobbIFfSWgG4',
    appId: '1:884285617554:ios:d9bd841de1b795895dbd4b',
    messagingSenderId: '884285617554',
    projectId: 'rede-social-app-b458e',
    storageBucket: 'rede-social-app-b458e.firebasestorage.app',
    iosBundleId: 'com.example.redeSocial',
  );
}
